# Generated by Django 4.2.27 on 2025-12-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mediafolder_media_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafolder',
            name='parent',
        ),
    ]
