# Generated by Django 4.2.27 on 2025-12-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mediafolder_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
