# Generated by Django 4.2.27 on 2025-12-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_media_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
