# Generated by Django 4.2.27 on 2025-12-14 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sede_activity_sede_catalog_sede_component_sede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_sedes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='sedes',
            field=models.ManyToManyField(blank=True, related_name='members', to='api.sede'),
        ),
        migrations.CreateModel(
            name='SedeSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('media', 'Mídia'), ('catalog', 'Catálogos'), ('all', 'Todos')], default='all', max_length=20)),
                ('permission_level', models.CharField(choices=[('read', 'Somente Leitura'), ('write', 'Leitura e Escrita')], default='read', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_sent', to='api.sede')),
                ('target_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to='api.sede')),
            ],
            options={
                'unique_together': {('source_sede', 'target_sede', 'resource_type')},
            },
        ),
    ]
