# Generated by Django 4.2.27 on 2025-12-16 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sede_responsible_user_user_sedes_sedesharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_org', to='api.sede'),
        ),
    ]
