# Generated by Django 4.2.27 on 2025-12-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_category_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dropshipping_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
