# Generated by Django 4.2.27 on 2025-12-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_product_dropshipping_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
