# Generated by Django 4.2.27 on 2025-12-21 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_catalog_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_catalogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalog',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='saved_catalogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='saved_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
