# Generated by Django 4.2.27 on 2025-12-21 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_catalog_likes_catalog_saves_product_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_covers', to='api.media'),
        ),
    ]
