# Generated by Django 4.2.27 on 2025-12-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_activity_options_activity_catalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='public_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
