# Generated by Django 5.2.9 on 2025-12-28 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_product_cover_image_alter_product_image_productmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='profiles/covers/')),
                ('profile_type', models.CharField(choices=[('empresa', 'Empresa'), ('criador', 'Criador'), ('revendedor', 'Revendedor')], max_length=20)),
                ('segments', models.JSONField(default=list)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(default='Brasil', max_length=50)),
                ('visibility', models.CharField(choices=[('publico', 'Público'), ('semi-publico', 'Semi-Público'), ('privado', 'Privado')], default='publico', max_length=20)),
                ('show_in_search', models.BooleanField(default=True)),
                ('allow_messages', models.BooleanField(default=True)),
                ('allow_follows', models.BooleanField(default=True)),
                ('show_followers_count', models.BooleanField(default=True)),
                ('show_catalog_count', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Público',
                'verbose_name_plural': 'Perfis Públicos',
                'db_table': 'public_profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_profiles', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='api.publicprofile')),
            ],
            options={
                'db_table': 'profile_saves',
            },
        ),
        migrations.CreateModel(
            name='ProfileFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('followed_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='api.publicprofile')),
            ],
            options={
                'db_table': 'profile_follows',
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocked_users',
                'indexes': [models.Index(fields=['blocker'], name='blocked_use_blocker_56191f_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.CreateModel(
            name='CatalogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_likes', to='api.catalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_likes',
                'indexes': [models.Index(fields=['catalog'], name='catalog_lik_catalog_950c10_idx')],
                'unique_together': {('user', 'catalog')},
            },
        ),
        migrations.CreateModel(
            name='CatalogView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_views', to='api.catalog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_views',
                'indexes': [models.Index(fields=['catalog', 'created_at'], name='catalog_vie_catalog_223ebe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='publicprofile',
            index=models.Index(fields=['username'], name='public_prof_usernam_adc3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='publicprofile',
            index=models.Index(fields=['profile_type'], name='public_prof_profile_89b99f_idx'),
        ),
        migrations.AddIndex(
            model_name='publicprofile',
            index=models.Index(fields=['show_in_search', 'visibility'], name='public_prof_show_in_b31524_idx'),
        ),
        migrations.AddIndex(
            model_name='profilesave',
            index=models.Index(fields=['user'], name='profile_sav_user_id_343074_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profilesave',
            unique_together={('user', 'profile')},
        ),
        migrations.AddIndex(
            model_name='profilefollow',
            index=models.Index(fields=['follower'], name='profile_fol_followe_d4c65d_idx'),
        ),
        migrations.AddIndex(
            model_name='profilefollow',
            index=models.Index(fields=['followed_profile'], name='profile_fol_followe_d22309_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profilefollow',
            unique_together={('follower', 'followed_profile')},
        ),
    ]
