# Generated by Django 5.2.15 on 2026-06-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_publicprofile_profilesave_profilefollow_blockeduser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="is_demo",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
