# Generated by Django 5.2.15 on 2026-09-09 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_catalog_is_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(default='free', max_length=50, unique=True)),
                ('monthly_token_quota', models.BigIntegerField(default=100000)),
                ('max_active_catalogs', models.PositiveIntegerField(default=5)),
                ('rate_limit_rpm', models.PositiveIntegerField(default=15)),
                ('can_use_council', models.BooleanField(default=False)),
                ('can_export_pdf', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nova Sessao', max_length=255)),
                ('active_agent', models.CharField(default='orchestrator', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'studio_chat_threads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], max_length=20)),
                ('agent_role', models.CharField(blank=True, default='', max_length=50)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatthread')),
            ],
            options={
                'db_table': 'studio_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudioCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('style_preset', models.CharField(default='editorial_clean', max_length=50)),
                ('primary_color', models.CharField(default='#111827', max_length=30)),
                ('secondary_color', models.CharField(default='#6366f1', max_length=30)),
                ('accent_color', models.CharField(default='#f59e0b', max_length=30)),
                ('font_family', models.CharField(default='Inter', max_length=100)),
                ('page_width', models.PositiveIntegerField(default=794)),
                ('page_height', models.PositiveIntegerField(default=1123)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_studio_catalogs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio_catalogs', to='api.organization')),
            ],
            options={
                'db_table': 'studio_catalogs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatthread',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='api.studiocatalog'),
        ),
        migrations.CreateModel(
            name='OrganizationQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_used_this_month', models.BigIntegerField(default=0)),
                ('billing_cycle_anchor', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='api.organization')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotas', to='api.subscriptionplan')),
            ],
            options={
                'db_table': 'organization_quotas',
            },
        ),
        migrations.CreateModel(
            name='CatalogSpread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spread_index', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('left_page_elements', models.JSONField(blank=True, default=list)),
                ('right_page_elements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreads', to='api.studiocatalog')),
            ],
            options={
                'db_table': 'catalog_spreads',
                'ordering': ['spread_index'],
                'unique_together': {('catalog', 'spread_index')},
            },
        ),
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_role', models.CharField(max_length=50)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('model_name', models.CharField(default='gemini-2.0-flash', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_logs', to='api.studiocatalog')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_logs', to='api.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'token_usage_logs',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='token_usage_organiz_10fe06_idx'), models.Index(fields=['agent_role'], name='token_usage_agent_r_c89063_idx')],
            },
        ),
    ]
