# Generated by Django 5.2.15 on 2026-09-09 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_subscriptionplan_chatthread_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('cover', 'Capa'), ('manifesto', 'Manifesto Editorial'), ('hero', 'Destaque Heroico (1 Produto)'), ('duo', 'Lamina Dupla (2 Produtos)'), ('single', 'Produto Individual'), ('grid_4', 'Grade Comercial (4 Produtos)'), ('divider', 'Divisor de Secao'), ('backcover', 'Contracapa'), ('full_catalog', 'Catalogo Completo')], default='hero', max_length=50)),
                ('industry', models.CharField(default='luxury_fashion', max_length=100)),
                ('style_preset', models.CharField(default='editorial_clean', max_length=50)),
                ('product_capacity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('editorial_reasoning', models.TextField(blank=True, default='')),
                ('blueprint_data', models.JSONField(blank=True, default=dict)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('thumbnail_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_templates', to='api.organization')),
            ],
            options={
                'db_table': 'catalog_templates',
                'ordering': ['category', 'title'],
            },
        ),
    ]
