# Generated by Django 5.2.15 on 2026-09-09 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_catalogtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_annual_brl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_monthly_brl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_brl', models.DecimalField(decimal_places=2, max_digits=8)),
                ('billing_interval', models.CharField(default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('paid', 'Pago'), ('pending', 'Pendente'), ('failed', 'Falhou'), ('refunded', 'Estornado')], default='paid', max_length=20)),
                ('payment_method_type', models.CharField(default='credit_card', max_length=20)),
                ('payment_method_summary', models.CharField(blank=True, default='', max_length=100)),
                ('receipt_code', models.CharField(max_length=64, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_invoices', to='api.organization')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='api.subscriptionplan')),
            ],
            options={
                'db_table': 'billing_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('trialing', 'Em Avaliacao'), ('past_due', 'Pendente'), ('canceled', 'Cancelada')], default='active', max_length=20)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Mensal'), ('annual', 'Anual')], default='monthly', max_length=20)),
                ('payment_method_type', models.CharField(choices=[('credit_card', 'Cartao de Credito'), ('pix', 'PIX'), ('none', 'Nenhum')], default='none', max_length=20)),
                ('payment_method_details', models.JSONField(blank=True, default=dict)),
                ('current_period_start', models.DateTimeField(auto_now_add=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.organization')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='api.subscriptionplan')),
            ],
            options={
                'db_table': 'organization_subscriptions',
            },
        ),
    ]
