# Generated by Django 5.2.15 on 2026-09-11 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_subscriptionplan_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=150)),
                ('mission', models.TextField()),
                ('decision_scope', models.TextField(blank=True, default='')),
                ('scope_constraints', models.TextField(blank=True, default='')),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('evaluation_keywords', models.JSONField(blank=True, default=list)),
                ('sample_prompts', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_agents', to='api.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_custom_agents',
                'ordering': ['name'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
