# Generated by Django 5.2.15 on 2026-09-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_user_clerk_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='external_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='gateway_provider',
            field=models.CharField(default='abacatepay', max_length=30),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='invoice_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='abacatepay_billing_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='abacatepay_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='abacatepay_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='last_webhook_event_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
