# Generated by Django 5.2.15 on 2026-09-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_billinginvoice_external_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiocatalog',
            name='brand_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studiocatalog',
            name='palette_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studiocatalog',
            name='total_pages',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
