# Generated by Django 5.2.15 on 2026-09-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_studiocatalog_brand_lock_studiocatalog_palette_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiocatalog',
            name='unassigned_products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
