# Generated by Django 5.2.15 on 2026-10-05 10:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_studiocatalog_unassigned_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='brand_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='catalog',
            name='brand_snapshot_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='catalog',
            name='brand_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studiocatalog',
            name='brand_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studiocatalog',
            name='brand_snapshot_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='studiocatalog',
            name='brand_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('segment', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True, max_length=2048)),
                ('logo_url', models.TextField(blank=True)),
                ('palette_name', models.CharField(blank=True, max_length=255)),
                ('custom_palette', models.JSONField(blank=True, default=dict)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('typography', models.JSONField(blank=True, default=dict)),
                ('visual_dna', models.JSONField(blank=True, default=dict)),
                ('tone_of_voice', models.TextField(blank=True)),
                ('commercial_contact', models.JSONField(blank=True, default=dict)),
                ('brand_markdown', models.TextField(blank=True)),
                ('intelligence', models.JSONField(blank=True, default=dict)),
                ('intelligence_fingerprint', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('legacy_id', models.CharField(blank=True, max_length=255)),
                ('legacy_source', models.JSONField(blank=True, default=dict)),
                ('migration_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_brands', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='api.organization')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalogs', to='api.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.brand'),
        ),
        migrations.AddField(
            model_name='studiocatalog',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studio_catalogs', to='api.brand'),
        ),
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('logo_primary', 'logo_primary'), ('logo_horizontal', 'logo_horizontal'), ('logo_vertical', 'logo_vertical'), ('symbol', 'symbol'), ('wordmark', 'wordmark'), ('logo_monochrome', 'logo_monochrome'), ('brand_manual', 'brand_manual'), ('moodboard', 'moodboard'), ('institutional_image', 'institutional_image'), ('font_reference', 'font_reference'), ('brand_document', 'brand_document')], max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('policy', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.brand')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_assets', to='api.media')),
            ],
        ),
        migrations.CreateModel(
            name='BrandGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MUST', 'Must'), ('PREFER', 'Prefer'), ('AVOID', 'Avoid')], default='PREFER', max_length=10)),
                ('category', models.CharField(default='other', max_length=40)),
                ('rule', models.TextField()),
                ('source', models.CharField(default='user_input', max_length=50)),
                ('source_text', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('status', models.CharField(choices=[('user_supplied', 'user_supplied'), ('inferred', 'inferred'), ('confirmed', 'confirmed'), ('rejected', 'rejected')], default='user_supplied', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidelines', to='api.brand')),
            ],
        ),
        migrations.CreateModel(
            name='BrandMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MUST', 'Must'), ('PREFER', 'Prefer'), ('AVOID', 'Avoid')], default='PREFER', max_length=10)),
                ('category', models.CharField(default='other', max_length=40)),
                ('rule', models.TextField()),
                ('source', models.CharField(default='user_input', max_length=50)),
                ('confidence', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('status', models.CharField(choices=[('user_supplied', 'user_supplied'), ('inferred', 'inferred'), ('confirmed', 'confirmed'), ('rejected', 'rejected')], default='user_supplied', max_length=20)),
                ('supporting_actions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='api.brand')),
                ('supporting_catalogs', models.ManyToManyField(blank=True, related_name='supported_brand_memories', to='api.studiocatalog')),
            ],
        ),
        migrations.CreateModel(
            name='BrandVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='api.brand')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_id', ''), _negated=True), fields=('organization', 'created_by', 'legacy_id'), name='brand_legacy_owner_unique'),
        ),
        migrations.AddConstraint(
            model_name='brandversion',
            constraint=models.UniqueConstraint(fields=('brand', 'number'), name='brand_version_number_unique'),
        ),
    ]
