# Generated by Django 5.2.15 on 2026-10-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_brand_intelligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiocatalog',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
