# Generated by Django 5.2.15 on 2026-10-05 18:17

import api.document_storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_studio_generation_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiocatalog',
            name='import_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='DocumentImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('filename', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('document_ir', models.JSONField(default=dict)),
                ('report', models.JSONField(default=dict)),
                ('previews', models.JSONField(default=list)),
                ('mode', models.CharField(default='preserve', max_length=20)),
                ('status', models.CharField(default='analyzing', max_length=20)),
                ('brand_snapshot', models.JSONField(blank=True, default=dict)),
                ('brand_snapshot_hash', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_imports', to='api.brand')),
                ('catalog', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_import', to='api.studiocatalog')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_imports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_imports', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentImportAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=api.document_storage.PrivateDocumentStorage(), upload_to='document_imports/')),
                ('kind', models.CharField(max_length=40)),
                ('source_hash', models.CharField(max_length=64)),
                ('width_pixels', models.PositiveIntegerField(blank=True, null=True)),
                ('height_pixels', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.documentimport')),
            ],
        ),
        migrations.AddField(
            model_name='documentimport',
            name='source_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.documentimportasset'),
        ),
    ]
