# Generated by Django 5.2.15 on 2026-10-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_document_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiocatalog',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studiocatalog',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16),
        ),
        migrations.AddIndex(
            model_name='studiocatalog',
            index=models.Index(fields=['organization', 'status'], name='studio_org_status_idx'),
        ),
    ]
