
export interface Product {
  code: string;
  name: string;
  description?: string;
  specs?: string;
  caixa?: string;
  imageUrl?: string;
  material?: string;
  internalDimensions?: string;
  externalDimensions?: string;
  usage?: string;
  category: 'Açougue & Frios' | 'Confeitaria' | 'Festa' | 'Food Service';
}

export const allProducts: Product[] = [
  // Açougue & Frios
  {
    code: 'FR-02',
    name: 'Embalagem Frios 2',
    material: 'PET',
    imageUrl: '/generated_catalog/FR-02.png',
    internalDimensions: '14x10x3cm',
    externalDimensions: '15x11x3.5cm',
    category: 'Açougue & Frios',
  },
  {
    code: 'FR-03',
    name: 'Embalagem Frios 3',
    material: 'PET',
    imageUrl: '/generated_catalog/FR-03.png',
    internalDimensions: '16x12x4cm',
    externalDimensions: '17x13x4.5cm',
    category: 'Açougue & Frios',
  },
  {
    code: 'FR-04',
    name: 'Embalagem Frios 4',
    material: 'PET',
    imageUrl: '/generated_catalog/FR-04.png',
    internalDimensions: '18x14x5cm',
    externalDimensions: '19x15x5.5cm',
    category: 'Açougue & Frios',
  },
  {
    code: 'FF-02',
    name: 'Embalagem Frios Fatiados 2',
    material: 'PET',
    imageUrl: '/generated_catalog/FF-02.png',
    internalDimensions: '12x9x2cm',
    externalDimensions: '13x10x2.5cm',
    category: 'Açougue & Frios',
  },
  {
    code: 'FF-03',
    name: 'Embalagem Frios Fatiados 3',
    material: 'PET',
    imageUrl: '/generated_catalog/FF-03.png',
    internalDimensions: '14x10x2.5cm',
    externalDimensions: '15x11x3cm',
    category: 'Açougue & Frios',
  },
  {
    code: 'FF-04',
    name: 'Embalagem Frios Fatiados 4',
    material: 'PET',
    imageUrl: '/generated_catalog/FF-04.png',
    internalDimensions: '16x12x3cm',
    externalDimensions: '17x13x3.5cm',
    category: 'Açougue & Frios',
  },
  {
    code: 'A-02',
    name: 'Embalagem Açougue 2',
    material: 'PET',
    imageUrl: '/generated_catalog/A-02.png',
    internalDimensions: '18x14x4cm',
    externalDimensions: '19x15x4.5cm',
    category: 'Açougue & Frios',
  },
  {
    code: 'A-03',
    name: 'Embalagem Açougue 3',
    material: 'PET',
    imageUrl: '/generated_catalog/A-03.png',
    internalDimensions: '20x16x5cm',
    externalDimensions: '21x17x5.5cm',
    category: 'Açougue & Frios',
  },
  {
    code: 'A-04',
    name: 'Embalagem Açougue 4',
    material: 'PET',
    imageUrl: '/generated_catalog/A-04.png',
    internalDimensions: '22x18x6cm',
    externalDimensions: '23x19x6.5cm',
    category: 'Açougue & Frios',
  },
  // Confeitaria
  {
    code: 'PF-08',
    name: 'Embalagem PET para doces e mini porções',
    material: 'PET cristal',
    internalDimensions: '172,5 × 90 × 39 mm',
    externalDimensions: '189 × 111,5 × 48 mm',
    usage: 'Ideal para doces, mini porções e pequenas sobremesas',
    imageUrl: '/generated_catalog/PF-08.png',
    category: 'Confeitaria',
  },
  {
    code: 'PF-10',
    name: 'Embalagem PET para doces médios',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Doces médios, sobremesas individuais',
    imageUrl: '/generated_catalog/PF-10.png',
    category: 'Confeitaria',
  },
  {
    code: 'PF-13',
    name: 'Embalagem PET para tortinhas pequenas',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Tortinhas pequenas, mini sobremesas',
    imageUrl: '/generated_catalog/PF-13.png',
    category: 'Confeitaria',
  },
  {
    code: 'PF-18',
    name: 'Embalagem PET para mini tortas médias',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Tortas pequenas, sobremesas de balcão',
    imageUrl: '/generated_catalog/PF-18.png',
    category: 'Confeitaria',
  },
  {
    code: 'PF-20',
    name: 'Embalagem PET para tortas pequenas',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Tortas menores e produtos de confeitaria leve',
    imageUrl: '/generated_catalog/PF-20.png',
    category: 'Confeitaria',
  },
  {
    code: 'PF-22',
    name: 'Embalagem PET para tortas médias',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Torta média, produtos decorados',
    imageUrl: '/generated_catalog/PF-22.png',
    category: 'Confeitaria',
  },
  {
    code: 'PF-25',
    name: 'Embalagem PET para tortas médias altas',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Tortas com mais altura e recheio',
    imageUrl: '/generated_catalog/PF-25.png',
    category: 'Confeitaria',
  },
  {
    code: 'PF-32A',
    name: 'Embalagem PET para tortas grandes',
    material: 'PET cristal',
    internalDimensions: '190 × 190 × 89 mm',
    externalDimensions: '216 × 216 × 98 mm',
    usage: 'Tortas grandes, bolos baixos, produtos para vitrine',
    imageUrl: '/generated_catalog/PF-32A.png',
    category: 'Confeitaria',
  },
  {
    code: 'PF-32B',
    name: 'Embalagem PET para tortas grandes (modelo B)',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Torta grande, bolo decorado',
    imageUrl: '/generated_catalog/PF-32B.png',
    category: 'Confeitaria',
  },
  {
    code: 'PF-50',
    name: 'Embalagem PET para tortas extragrandes',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Tortas grandes de confraternização',
    imageUrl: '/generated_catalog/PF-50.png',
    category: 'Confeitaria',
  },
  {
    code: 'PF-60',
    name: 'Embalagem PET para tortas premium',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Tortas especiais, bolos temáticos',
    imageUrl: '/catalogos/produtosConfeitaria/pf-60.png',
    category: 'Confeitaria',
  },
  {
    code: 'PF-70',
    name: 'Embalagem PET para tortas especiais altas',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Bolos e tortas com maior altura',
    imageUrl: '/catalogos/produtosConfeitaria/pf-70.png',
    category: 'Confeitaria',
  },
  {
    code: 'PF-80',
    name: 'Embalagem PET para tortas família',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Tortas extragrandes, bolos família',
    imageUrl: '/catalogos/produtosConfeitaria/pf-80.png',
    category: 'Confeitaria',
  },
  {
    code: 'POTE-250',
    name: 'Pote PET 250 ml',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Sobremesas, molhos, pequenas porções',
    imageUrl: '/catalogos/produtosConfeitaria/pote-pet-redondo.png',
    category: 'Confeitaria',
  },
  {
    code: 'POTE-300',
    name: 'Pote PET 300 ml',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Sobremesas, frutas picadas',
    imageUrl: '/catalogos/produtosConfeitaria/pote-pet-redondo.png',
    category: 'Confeitaria',
  },
  {
    code: 'POTE-350',
    name: 'Pote PET 350 ml',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Açaí, salada de frutas, porções médias',
    imageUrl: '/catalogos/produtosConfeitaria/pote-pet-redondo.png',
    category: 'Confeitaria',
  },
  {
    code: 'POTE-500',
    name: 'Pote PET 500 ml',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Porções maiores e sobremesas premium',
    imageUrl: '/catalogos/produtosConfeitaria/pote-pet-redondo.png',
    category: 'Confeitaria',
  },
  {
    code: 'POTE-750',
    name: 'Pote PET 750 ml',
    material: 'PET',
    internalDimensions: '',
    externalDimensions: '',
    usage: 'Sobremesas grandes, marmitinhas frias',
    imageUrl: '/catalogos/produtosConfeitaria/pote-pet-redondo.png',
    category: 'Confeitaria',
  },
  // Festa
  {
    code: 'LF-01',
    name: 'Caixa Quadrada Premium PET – Tampa Reta',
    material: 'PET',
    imageUrl: '/catalogos/linhaFestaSemFundo/lf-01.png',
    internalDimensions: '15x15x10cm',
    externalDimensions: '16x16x11cm',
    category: 'Festa',
  },
  {
    code: 'LF-02',
    name: 'Caixa para Brigadeiros/Doces – 6 Unidades',
    material: 'PET Cristal',
    imageUrl: '/catalogos/linhaFestaSemFundo/lf-02.png',
    internalDimensions: '18x12x4cm',
    externalDimensions: '19x13x5cm',
    category: 'Festa',
  },
  {
    code: 'LF-03',
    name: 'Cúpula para Mini Bolo – Redondo 12/14 cm',
    material: 'PET Cristal',
    imageUrl: '/catalogos/linhaFestaSemFundo/lf-03.png',
    internalDimensions: 'Ø12-14cm',
    externalDimensions: 'Ø13-15cm',
    category: 'Festa',
  },
  {
    code: 'LF-04',
    name: 'Embalagem para Fatia de Bolo (Triangular)',
    material: 'PET',
    imageUrl: '/catalogos/linhaFestaSemFundo/lf-04.png',
    internalDimensions: '12x8x10cm',
    externalDimensions: '13x9x11cm',
    category: 'Festa',
  },
  {
    code: 'LF-05',
    name: 'Embalagem para Torta/Salgados – 500/600 ml',
    material: 'PET Cristal',
    imageUrl: '/catalogos/linhaFestaSemFundo/lf-05.png',
    internalDimensions: '500-600ml',
    externalDimensions: '14x14x6cm',
    category: 'Festa',
  },
  {
    code: 'LF-06',
    name: 'Marmita/Caixa Take Away – Tampa Articulada',
    material: 'PP/PET Colorida',
    imageUrl: '/catalogos/linhaFestaSemFundo/lf-06.png',
    internalDimensions: '18x12x7cm',
    externalDimensions: '19x13x8cm',
    category: 'Festa',
  },
  {
    code: 'LF-07',
    name: 'Pote Diamante P (Pequeno)',
    material: 'PET',
    imageUrl: '/catalogos/linhaFestaSemFundo/lf-07.png',
    internalDimensions: '250ml',
    externalDimensions: '8x8x8cm',
    category: 'Festa',
  },
  {
    code: 'LF-08',
    name: 'Pote Diamante G (Grande)',
    material: 'PET',
    imageUrl: '/catalogos/linhaFestaSemFundo/lf-08.png',
    internalDimensions: '750ml',
    externalDimensions: '12x12x12cm',
    category: 'Festa',
  },
  {
    code: 'LF-09',
    name: 'Pote Redondo com Tampa – 500/750/1000 ml',
    material: 'PET ou PP',
    imageUrl: '/catalogos/linhaFestaSemFundo/lf-09.png',
    internalDimensions: '500-1000ml',
    externalDimensions: 'Ø12-15cm',
    category: 'Festa',
  },
  // Food Service
  {
    code: 'FS-01',
    name: 'Pote Térmico HF-01',
    material: 'EPS',
    imageUrl: '/catalogos/foodServiceSemFundo/fs-01.png',
    internalDimensions: '500ml',
    externalDimensions: 'Ø11x8cm',
    category: 'Food Service',
  },
  {
    code: 'FS-02',
    name: 'Embalagem Food Service - Pequena',
    material: 'PET',
    imageUrl: '/catalogos/foodServiceSemFundo/fs-02.png',
    internalDimensions: '12x10x5cm',
    externalDimensions: '13x11x5.5cm',
    category: 'Food Service',
  },
  {
    code: 'FS-03',
    name: 'Embalagem Food Service - Média',
    material: 'PET',
    imageUrl: '/catalogos/foodServiceSemFundo/fs-03.png',
    internalDimensions: '15x12x6cm',
    externalDimensions: '16x13x6.5cm',
    category: 'Food Service',
  },
  {
    code: 'FS-04',
    name: 'Embalagem Food Service - Média Plus',
    material: 'PET',
    imageUrl: '/catalogos/foodServiceSemFundo/fs-04.png',
    internalDimensions: '16x13x6cm',
    externalDimensions: '17x14x6.5cm',
    category: 'Food Service',
  },
  {
    code: 'FS-05',
    name: 'Embalagem Food Service - Standard',
    material: 'PET',
    imageUrl: '/catalogos/foodServiceSemFundo/fs-05.png',
    internalDimensions: '18x14x7cm',
    externalDimensions: '19x15x7.5cm',
    category: 'Food Service',
  },
  {
    code: 'FS-06',
    name: 'Embalagem Food Service - Large',
    material: 'PET',
    imageUrl: '/catalogos/foodServiceSemFundo/fs-06.png',
    internalDimensions: '20x16x8cm',
    externalDimensions: '21x17x8.5cm',
    category: 'Food Service',
  },
  {
    code: 'FS-07',
    name: 'Embalagem Food Service - Grande',
    material: 'PET',
    imageUrl: '/catalogos/foodServiceSemFundo/fs-07.png',
    internalDimensions: '22x18x9cm',
    externalDimensions: '23x19x9.5cm',
    category: 'Food Service',
  },
  {
    code: 'FS-08',
    name: 'Pote Térmico EPS',
    material: 'EPS',
    imageUrl: '/catalogos/foodServiceSemFundo/fs-08.png',
    internalDimensions: '750ml',
    externalDimensions: 'Ø13x10cm',
    category: 'Food Service',
  },
];
